// guide.js
// Guía de dudas del embarazo y el posparto.
// Embarazo: transcrito de "Dudas frecuentes en el embarazo, semana a semana" (equipo de Vera).
// Las respuestas marcadas con `draft: true` las ha redactado el equipo técnico y están pendientes
// de revisión clínica.
// Cada respuesta es una lista de bloques: un texto es un párrafo; un array es una lista.

export const GUIDE_INTRO = 'Estas son las preguntas más habituales, ordenadas por el momento en que suelen aparecer. Las respuestas siguen el circuito de la sanidad pública en España; los calendarios exactos pueden variar según tu comunidad autónoma y tu hospital. Esta guía informa, pero no sustituye a tu matrona ni a tu ginecólogo.';

export const PREGNANCY_GUIDE = [
  {
    id: 's4', from: 4, to: 10, title: 'Semanas 4 a 10', subtitle: 'Acabas de saber que estás embarazada',
    items: [
      { q: '¿Cuándo pido la primera cita y con quién?', a: ['En cuanto tengas el test positivo, pide cita en tu centro de salud con la matrona o con tu médico de familia. Te abrirán la cartilla del embarazo, te pedirán la primera analítica y te derivarán para la primera ecografía. Lo ideal es que esta primera visita sea antes de la semana 10.'] },
      { q: '¿Cómo se cuentan las semanas?', a: ['Se cuentan desde el primer día de tu última regla, no desde la concepción. Por eso, cuando te das cuenta de la falta, ya estás de unas 4 o 5 semanas. La fecha probable de parto es la semana 40, pero lo normal es dar a luz entre la 37 y la 42.'] },
      { q: '¿Tengo que tomar ácido fólico? ¿Y yodo o hierro?', a: ['Sí al ácido fólico: reduce el riesgo de defectos en la columna del bebé. Lo ideal es empezarlo antes de quedarte embarazada y mantenerlo al menos hasta la semana 12. El yodo también se suele recomendar durante todo el embarazo y la lactancia, además de usar sal yodada. El hierro solo hace falta si la analítica muestra anemia o reservas bajas.'] },
      { q: '¿Es verdad que hay que comer por dos?', a: ['No. En el primer trimestre no necesitas comer más. A partir del segundo, basta con un poco más al día, el equivalente a un tentempié sano. Importa más la calidad: fruta, verdura, legumbres, cereales integrales, lácteos, huevo y pescado.'] },
      { q: '¿Qué alimentos debo evitar?', a: ['Los que pueden transmitir infecciones como la listeria o la toxoplasmosis:', [
        'Carne cruda o poco hecha (carpaccio, steak tartar, carne rosada por dentro).',
        'Quesos de leche cruda y leche sin pasteurizar. Los quesos pasteurizados, curados o frescos, sí puedes tomarlos.',
        'Pescado crudo o ahumado refrigerado (sushi, ceviche, salmón ahumado), salvo que esté cocinado.',
        'Patés refrigerados y brotes crudos (soja, alfalfa).',
        'Huevo crudo o poco hecho (mayonesa casera, tiramisú).',
        'Alcohol: ninguna cantidad es segura durante el embarazo.']] },
      { q: '¿Puedo comer jamón y embutidos?', toxo: true, a: ['Depende de si eres inmune a la toxoplasmosis, algo que te dirá la primera analítica. Si no lo eres, se recomienda evitar los embutidos crudos curados (jamón, chorizo, salchichón, lomo). Congelarlos reduce el riesgo de toxoplasmosis, pero no elimina la listeria. Si ya eres inmune, no hay problema. Los embutidos cocidos, como el jamón de york o la pechuga de pavo, se pueden tomar.'] },
      { q: 'Si no soy inmune a la toxoplasmosis, ¿qué más tengo que hacer?', toxo: true, a: ['Lava muy bien frutas, verduras y hierbas frescas, aunque vengan envasadas. Lávate las manos después de tocar carne cruda o tierra, y usa guantes en el jardín. Puedes tener gato: simplemente que otra persona limpie su arenero cada día, o usa guantes si lo haces tú.'] },
      { q: '¿Cuánto café puedo tomar?', a: ['Hasta unos 200 mg de cafeína al día, que equivale a uno o dos cafés. Recuerda que el té, los refrescos de cola, las bebidas energéticas y el chocolate también llevan cafeína.'] },
      { q: '¿Qué medicamentos puedo tomar?', a: ['Para el dolor o la fiebre, el paracetamol es la opción de elección. Evita el ibuprofeno y otros antiinflamatorios salvo que te los indique tu médico, y no los tomes nunca a partir de la semana 20. Antes de tomar cualquier otro medicamento, suplemento o planta medicinal, consulta.'] },
      { q: 'Tomo medicación habitual, ¿la dejo?', a: ['No la dejes por tu cuenta: para algunas enfermedades es más peligroso suspenderla que seguir. Coméntalo cuanto antes con quien te la receta, que valorará si hay que ajustarla o cambiarla.'] },
      { q: '¿Son normales las náuseas? ¿Hasta cuándo duran?', a: ['Sí, son muy frecuentes y suelen mejorar hacia la semana 12 a 16. Ayuda comer poco y a menudo, evitar el estómago vacío, tomar algo seco al levantarte y evitar olores fuertes. Si vomitas todo lo que comes o bebes, o pierdes peso, consulta: existe tratamiento.'] },
      { q: '¿Es normal manchar un poco al principio?', a: ['Un manchado leve puede ser normal en las primeras semanas. Aun así, coméntalo siempre. Ve a urgencias si el sangrado es como una regla o mayor, o si se acompaña de dolor intenso en la tripa, sobre todo en un lado.'] },
    ],
  },
  {
    id: 's11', from: 11, to: 14, title: 'Semanas 11 a 14', subtitle: 'Primera ecografía y cribado',
    items: [
      { q: '¿Cuántas ecografías me harán?', a: ['En un embarazo sin complicaciones, la sanidad pública hace tres: una entre las semanas 11 y 14, la morfológica hacia la semana 20 y otra en el tercer trimestre, hacia la 32 a 36. Si hace falta vigilar algo, te harán más.'] },
      { q: '¿Qué se ve en la primera ecografía?', a: ['Se confirma que el embarazo está bien situado, cuántos bebés hay y que el corazón late. También se ajusta la fecha probable de parto según el tamaño del bebé y se mide el pliegue de la nuca, que forma parte del cribado.'] },
      { q: '¿Qué es el cribado combinado del primer trimestre?', a: ['Es una prueba que calcula la probabilidad de que el bebé tenga algunas alteraciones cromosómicas, como el síndrome de Down. Combina tu edad, un análisis de sangre y la medida de la nuca en la ecografía. No da un diagnóstico: solo dice si la probabilidad es baja o alta.'] },
      { q: '¿Y si sale de riesgo alto?', a: ['No significa que el bebé tenga un problema; la mayoría de los bebés con resultado de riesgo alto están sanos. Te explicarán las opciones: un test de ADN fetal en sangre o una prueba diagnóstica (biopsia de corion o amniocentesis). Tú decides qué hacer con toda la información.'] },
      { q: '¿Merece la pena hacerme el test de ADN fetal?', a: ['Es un análisis de tu sangre muy fiable para detectar las alteraciones cromosómicas más frecuentes, aunque tampoco es diagnóstico. En la sanidad pública se ofrece sobre todo cuando el cribado sale de riesgo alto o intermedio. Si quieres hacértelo sin esa indicación, suele ser por la privada.'] },
      { q: '¿Qué me miran en la analítica del primer trimestre?', a: ['Tu grupo sanguíneo y Rh, si tienes anemia, la glucosa, un análisis de orina y tu inmunidad frente a infecciones que pueden afectar al bebé: rubéola, toxoplasmosis, sífilis, hepatitis B, VIH y, en algunos centros, otras. Según los resultados te darán recomendaciones concretas.'] },
    ],
  },
  {
    id: 's15', from: 15, to: 23, title: 'Semanas 15 a 23', subtitle: 'Ecografía morfológica y primeros movimientos',
    items: [
      { q: '¿Qué es la ecografía de la semana 20?', a: ['Es la ecografía morfológica, la más detallada del embarazo. Se revisan uno por uno los órganos del bebé, la placenta y el líquido amniótico. Suele durar más que las otras y, si el bebé está en mala postura, a veces hay que repetirla otro día.'] },
      { q: '¿Cuándo voy a notar al bebé moverse?', a: ['En el primer embarazo, normalmente entre las semanas 18 y 22; si ya has tenido hijos, puede ser antes. Al principio se nota como burbujas o cosquillas. A partir de la semana 24 o 26 los movimientos se vuelven más claros y regulares.'] },
      { q: '¿Cuánto peso es normal ganar?', a: ['Depende de tu peso de partida. Si empiezas con un peso normal, lo habitual es ganar entre 11 y 16 kilos en todo el embarazo. Si partes con sobrepeso, algo menos; si partes con bajo peso, algo más. Tu matrona te irá pesando en cada visita.'] },
      { q: '¿Puedo hacer ejercicio?', a: ['Sí, y es muy recomendable. Lo ideal es unos 150 minutos a la semana de actividad moderada: caminar, nadar, bici estática, yoga o pilates para embarazadas. Evita deportes de contacto, con riesgo de caída o de golpes en la tripa, y el buceo con botella. Si ya hacías deporte, probablemente puedas seguir adaptándolo.'] },
      { q: '¿Puedo tener relaciones sexuales?', a: ['Sí, en un embarazo normal no hay ningún problema y no le hacen daño al bebé. Te dirán que las evites si tienes sangrados, placenta previa, riesgo de parto prematuro o has roto la bolsa.'] },
      { q: '¿Puedo viajar en avión?', a: ['Sí. El segundo trimestre es el momento más cómodo. En un embarazo de un solo bebé se puede volar hasta la semana 36, aunque muchas aerolíneas piden un informe médico a partir de la 28. En vuelos largos, levántate a caminar, bebe agua y valora usar medias de compresión. Antes de viajar, comprueba que tu destino no tenga riesgo de infecciones como el zika.'] },
      { q: '¿Puedo ir a la sauna, al spa o a la piscina?', a: ['A la piscina, sí. Evita la sauna, los baños turcos y los jacuzzis muy calientes, sobre todo en el primer trimestre, porque subir mucho la temperatura del cuerpo no es bueno para el bebé.'] },
      { q: '¿Puedo ir al dentista o hacerme una radiografía?', a: ['Sí. Ir al dentista es recomendable, porque las encías se inflaman y sangran más en el embarazo. La anestesia local dental es segura, y una radiografía dental con protección también. Avisa siempre de que estás embarazada.'] },
      { q: '¿Puedo teñirme el pelo o usar mis cosméticos?', a: ['Los tintes parecen seguros; si quieres ser prudente, espera al segundo trimestre y ventila bien. En cosmética, evita los retinoides (retinol, tretinoína), que están desaconsejados. Protector solar y cremas hidratantes, sin problema.'] },
      { q: '¿Hay alguna postura mejor para dormir?', a: ['A partir del segundo trimestre es mejor dormir de lado, preferiblemente sobre el izquierdo. Boca arriba, el peso del útero puede comprimir vasos sanguíneos y hacer que te marees. Si te despiertas boca arriba, no pasa nada: simplemente vuelve a ponerte de lado. Un cojín entre las piernas ayuda.'] },
    ],
  },
  {
    id: 's24', from: 24, to: 28, title: 'Semanas 24 a 28', subtitle: 'Control del azúcar y vacunas',
    items: [
      { q: '¿Qué es el test de O\'Sullivan?', a: ['Es una prueba para detectar la diabetes del embarazo. Se hace entre las semanas 24 y 28: te sacan sangre una hora después de tomar una bebida con azúcar. Hay que ir en ayunas. Si tienes factores de riesgo, como sobrepeso o diabetes en la familia, puede que te la hagan también en el primer trimestre.'] },
      { q: '¿Y si el O\'Sullivan sale alterado?', a: ['No quiere decir que tengas diabetes. Solo indica que hay que hacer una prueba más larga (la sobrecarga oral de glucosa), que sí confirma o descarta el diagnóstico. La mayoría de las mujeres con un O\'Sullivan alterado no tienen diabetes.'] },
      { q: 'Soy Rh negativo, ¿qué significa?', rh: true, a: ['Si tú eres Rh negativo y el bebé es Rh positivo, tu cuerpo podría fabricar defensas contra su sangre, lo que afectaría a futuros embarazos. Para evitarlo te pondrán una inyección de inmunoglobulina anti-D hacia la semana 28 y otra tras el parto si el bebé es Rh positivo. También si tienes un sangrado, un golpe en la tripa o una amniocentesis.'] },
      { q: '¿Qué vacunas me tengo que poner?', a: ['Tres, todas seguras en el embarazo:', [
        'Tosferina (dTpa): en cada embarazo, preferiblemente entre las semanas 27 y 28. Tus defensas pasan al bebé y lo protegen en sus primeros meses, cuando aún no puede vacunarse.',
        'Gripe: si estás embarazada durante la campaña de otoño e invierno, en cualquier trimestre. Te protege a ti y al bebé.',
        'COVID-19: también se recomienda durante la campaña, en cualquier trimestre.']] },
      { q: '¿Por qué la tosferina en cada embarazo, si ya me vacuné?', a: ['Porque las defensas bajan con el tiempo y lo que se busca es que tengas muchas justo antes del parto para pasárselas al bebé. Por eso se repite en cada embarazo, aunque sean seguidos.'] },
      { q: '¿Y la del virus respiratorio sincitial (VRS), la de la bronquiolitis?', a: ['Existe una vacuna para embarazadas, pero en España la estrategia principal es proteger directamente al bebé con un anticuerpo (nirsevimab) que se le pone al nacer o al empezar la temporada de invierno. Pregunta a tu matrona cómo lo organiza tu comunidad.'] },
      { q: '¿Hay vacunas que no me puedo poner?', a: ['Sí, las de virus vivos, como la triple vírica (sarampión, rubéola, paperas) y la de la varicela. Si no estás protegida, te las pondrán después del parto, y se pueden poner durante la lactancia.'] },
      { q: '¿Tiene que vacunarse también mi pareja o la familia?', a: ['Es muy recomendable que las personas que van a convivir con el bebé estén al día de sus vacunas, sobre todo la de la gripe y la tosferina. Así forman un escudo alrededor del recién nacido.'] },
    ],
  },
  {
    id: 's29', from: 29, to: 36, title: 'Semanas 29 a 36', subtitle: 'Tercer trimestre y preparación',
    items: [
      { q: '¿Qué se mira en la ecografía del tercer trimestre?', a: ['Se hace entre las semanas 32 y 36. Sirve sobre todo para ver cómo está creciendo el bebé, en qué postura está (de cabeza o de nalgas), dónde está la placenta y cuánto líquido hay. El peso que se calcula es aproximado, con un margen de error de un 10 a 15 %.'] },
      { q: '¿Cuándo empiezan las clases de preparación al parto?', a: ['La matrona de tu centro de salud suele organizarlas a partir de la semana 28 a 30. Son gratuitas y muy recomendables: se habla del parto, la respiración, la lactancia y los primeros cuidados del bebé. Tu pareja o acompañante puede ir contigo.'] },
      { q: '¿Qué es un plan de parto?', a: ['Es un documento donde explicas tus preferencias para el parto: acompañante, anestesia, postura, piel con piel, lactancia, etc. Muchos hospitales tienen su propio modelo. Entrégalo hacia la semana 32 a 36 y repásalo con tu matrona. Ten en cuenta que, si surge algo durante el parto, el equipo puede tener que cambiar el plan por tu seguridad o la del bebé.', { link: 'https://www.sanidad.gob.es/organizacion/sns/planCalidadSNS/pdf/equidad/planPartoNacimiento.pdf', text: 'Descargar el modelo de plan de parto y nacimiento del Ministerio de Sanidad (PDF)' }] },
      { q: '¿Para qué es el exudado vaginal y rectal?', a: ['Entre las semanas 35 y 37 se toma una muestra con un bastoncillo para saber si tienes una bacteria llamada estreptococo del grupo B. Es muy habitual y a ti no te causa problemas, pero podría afectar al bebé al nacer. Si sale positivo, te pondrán antibiótico durante el parto y queda resuelto.'] },
      { q: '¿Qué hago con el ardor, el estreñimiento y las hemorroides?', a: ['Para el ardor: comidas pequeñas, no tumbarte justo después de comer y elevar un poco la cabecera de la cama; si no basta, hay antiácidos seguros. Para el estreñimiento: fibra, agua y moverte a diario. Si aparecen hemorroides, evitar el estreñimiento es lo principal; tu médico puede recetarte una pomada.'] },
      { q: '¿Por qué tengo calambres, piernas hinchadas o dolor de espalda?', a: ['Son molestias muy frecuentes por el peso, las hormonas y la circulación. Ayuda caminar, estirar, elevar las piernas al descansar, usar medias de compresión y evitar estar mucho tiempo de pie. Consulta si la hinchazón aparece de golpe, afecta a la cara o las manos, o una pierna está más hinchada, roja y dolorosa que la otra.'] },
      { q: '¿Qué son las contracciones de Braxton Hicks?', a: ['Son contracciones de "ensayo": la tripa se pone dura unos segundos, sin dolor o con una molestia leve, y son irregulares. Son normales y no significan que empiece el parto. Si se vuelven regulares, dolorosas o muy frecuentes antes de la semana 37, consulta.'] },
      { draft: true, q: '¿Qué es el masaje perineal y cuándo empiezo?', a: ['Es un masaje suave de la zona entre la vagina y el ano (el periné) que lo prepara para estirarse durante el parto. En un primer parto, hacerlo desde la semana 34 o 35 reduce el riesgo de desgarros que necesitan puntos y de episiotomía.', ['Puedes hacerlo tú o tu pareja, unos 5 minutos, varias veces a la semana.', 'Con las manos limpias y un aceite neutro (de almendras o de oliva, por ejemplo).', 'Presiona hacia abajo y hacia los lados hasta notar un ligero escozor, sin llegar a doler.'], 'No lo hagas si tienes una infección vaginal, sangrado o te han dicho que tienes placenta previa. Tu matrona puede enseñarte cómo hacerlo.'] },
      { draft: true, q: 'Desde la semana 36: ¿cuándo debo ir al hospital?', a: ['Ve al hospital, sin esperar a la siguiente cita, si notas:', ['Contracciones regulares y dolorosas, cada 5 minutos durante al menos 1 hora (algo antes si ya has tenido partos).', 'Que rompes la bolsa o pierdes líquido, aunque no tengas contracciones.', 'Sangrado como una regla o más.', 'Que el bebé se mueve menos de lo habitual.', 'Dolor de cabeza fuerte que no se va, visión borrosa o lucecitas, o hinchazón brusca de cara y manos.', 'Picor intenso en las palmas de las manos y las plantas de los pies, sobre todo por la noche.', 'Fiebre de 38 °C o más.']] },
      { draft: true, q: '¿Por qué me preguntan si me pican las palmas de las manos?', a: ['Porque un picor intenso en las palmas y las plantas de los pies, sobre todo por la noche y sin granos, puede ser una colestasis del embarazo: un problema del hígado que necesita un análisis y vigilar más de cerca al bebé. El picor leve de la tripa por la piel que se estira es normal; el de manos y pies conviene consultarlo pronto.'] },
      { draft: true, q: '¿Y si tengo dolor de cabeza al final del embarazo?', a: ['Un dolor de cabeza leve que mejora con descanso y paracetamol suele no ser importante. Pero un dolor de cabeza fuerte que no se va, sobre todo si se acompaña de visión borrosa, lucecitas, dolor en la boca del estómago o hinchazón brusca de cara y manos, puede ser una preeclampsia (una subida de tensión propia del embarazo): ve al hospital para que te tomen la tensión.'] },
      { q: '¿Cómo sé si el bebé se mueve lo suficiente?', a: ['No hay un número exacto: lo importante es que conozcas su patrón habitual. Si notas que se mueve menos de lo normal, túmbate de lado un rato y concéntrate en sus movimientos. Si sigues notándolo menos, ve a urgencias ese mismo día: no esperes al día siguiente.'] },
      { q: '¿Tengo derecho a baja durante el embarazo?', a: ['Si tu trabajo tiene riesgos para el embarazo (esfuerzo físico, turnos nocturnos, productos tóxicos, radiaciones…) y la empresa no puede adaptarte el puesto, puedes pedir la prestación por riesgo durante el embarazo. Si tienes una complicación médica, tu médico puede darte una baja por incapacidad temporal. El embarazo en sí no es motivo de baja.'] },
      { q: '¿Tengo permiso para ir a las revisiones y a las clases?', a: ['Sí. La ley te reconoce permiso retribuido para exámenes prenatales y preparación al parto que coincidan con tu horario de trabajo. Avisa a tu empresa con antelación y lleva justificante.'] },
      { q: '¿Cuánto dura el permiso por nacimiento?', a: ['Desde 2025 son 19 semanas para cada progenitor, pagadas al 100 % por la Seguridad Social. Las 6 primeras tras el parto son obligatorias; 17 semanas se disfrutan hasta que el bebé cumple un año y las otras 2 hasta que cumple 8. En familias monoparentales son 32 semanas. La madre puede empezar el permiso hasta 4 semanas antes de la fecha probable de parto.'] },
    ],
  },
  {
    id: 's37', from: 37, to: 42, title: 'Semanas 37 a 42', subtitle: 'La recta final y el parto',
    items: [
      { q: '¿Cuándo se considera que el embarazo está "a término"?', a: ['Desde la semana 37 hasta la 41 y 6 días. Dar a luz en cualquier momento de ese periodo es normal; solo una minoría de bebés nace justo el día de la fecha probable de parto.'] },
      { q: '¿Qué pasa si me paso de fecha?', a: ['A partir de la semana 40 te harán controles más frecuentes. Si el parto no empieza solo, lo habitual es proponerte provocarlo (inducirlo) durante la semana 41, para no llegar a la 42, cuando aumentan los riesgos para el bebé.'] },
      { q: '¿Qué es la monitorización?', a: ['Es un registro del latido del bebé y de las contracciones, con dos sensores sujetos a la tripa durante unos 20 a 30 minutos. Según el hospital, se empieza a hacer hacia la semana 40 o antes si hay algún motivo.'] },
      { draft: true, q: '¿Qué diferencia hay entre la monitorización continua y la intermitente?', a: ['Durante el parto se vigila el latido del bebé de dos maneras:', ['Intermitente: la matrona escucha el latido cada cierto tiempo con un pequeño aparato (Doppler). Es lo habitual en un parto de bajo riesgo y te deja moverte con más libertad.', 'Continua: llevas dos sensores sujetos a la tripa que registran el latido y las contracciones todo el tiempo. Se usa cuando hay algún factor de riesgo, con la epidural o con medicación para acelerar el parto, o si el latido necesita vigilarse más de cerca.'], 'Muchos hospitales tienen monitores inalámbricos que permiten moverse aunque la monitorización sea continua. Puedes preguntar cuál usan en el tuyo.'] },
      { q: '¿Cuándo tengo que ir al hospital?', a: [[
        'Si las contracciones son regulares y dolorosas, cada 5 minutos durante al menos 1 hora (si ya has tenido partos, algo antes).',
        'Si rompes la bolsa, aunque no tengas contracciones.',
        'Si sangras como una regla o más.',
        'Si notas que el bebé se mueve menos.'], 'Si vives lejos del hospital o tu matrona te ha indicado otra cosa, sigue sus instrucciones.'] },
      { q: '¿Cómo sé si he roto aguas?', a: ['Notarás salir líquido por la vagina que no puedes controlar: puede ser un chorro o un goteo continuo que moja la ropa. Suele ser transparente y huele poco. Si es verde, marrón o con sangre, ve al hospital sin esperar. Si tienes dudas, ponte una compresa, obsérvala un rato y consulta.'] },
      { q: '¿Qué llevo en la bolsa del hospital?', a: ['Tu DNI, tarjeta sanitaria, cartilla del embarazo e informes, el plan de parto, ropa cómoda y camisón que se abra por delante, sujetadores de lactancia, bragas cómodas o desechables, compresas de posparto, neceser y cargador. Para el bebé: bodies, pijamas, gorro, calcetines, pañales de recién nacido y la ropa para salir. Y la sillita del coche instalada para volver a casa.'] },
      { q: '¿Cuándo puedo pedir la epidural?', a: ['Cuando estés en fase activa del parto y la necesites; no hay que esperar a una dilatación concreta. Antes, el anestesista revisará que tu analítica y tu coagulación están bien. También hay otras opciones para el dolor: moverte, la pelota, el agua caliente o el óxido nitroso, según el hospital.'] },
      { q: '¿Qué es el piel con piel?', a: ['Es poner al bebé desnudo sobre tu pecho nada más nacer, tapados los dos. Le ayuda a regular su temperatura, se calma antes y facilita que empiece a mamar. Si el parto es por cesárea, muchos hospitales también lo hacen, o lo hace tu acompañante mientras terminan.'] },
      { q: '¿Qué es el pinzamiento tardío del cordón?', a: ['Es esperar un par de minutos antes de cortar el cordón, en lugar de hacerlo inmediatamente. Así pasa más sangre de la placenta al bebé, lo que mejora sus reservas de hierro. Hoy es lo habitual si el bebé nace bien.'] },
    ],
  },
  {
    id: 'emo', from: 0, to: 42, title: 'En cualquier semana', subtitle: 'Cómo te sientes',
    items: [
      { q: '¿Es normal sentirme triste o ansiosa en el embarazo?', a: ['Los cambios de humor son frecuentes, pero la tristeza o la ansiedad que duran semanas, te quitan el sueño o las ganas de todo no son "lo normal del embarazo". Coméntalo con tu matrona o tu médico: tiene tratamiento y pedir ayuda es lo mejor para ti y para el bebé.'] },
      { q: '¿Cómo me preparo para la lactancia?', a: ['No hace falta preparar el pecho. Lo que más ayuda es informarte antes: en las clases de preparación, con tu matrona o en un grupo de apoyo a la lactancia. Tras el parto, el piel con piel y poner al bebé al pecho pronto y a demanda facilitan que todo arranque. Si duele o notas que algo no va bien, pide ayuda pronto: casi todo tiene solución.'] },
    ],
  },
];

export const POSTPARTUM_GUIDE = [
  {
    id: 'pp', title: 'Después del parto', subtitle: 'Las primeras semanas',
    items: [
      { q: '¿Cómo distingo la tristeza posparto de una depresión?', a: ['La tristeza posparto (baby blues) es muy común: llanto fácil, sensibilidad y cansancio en los primeros días, que se pasan solos en unas dos semanas. Si dura más, va a peor, no disfrutas de nada, te sientes incapaz o tienes pensamientos de hacerte daño a ti o al bebé, puede ser una depresión posparto. Pide ayuda cuanto antes; si esos pensamientos aparecen, ve a urgencias o llama al 112.'] },
      { q: '¿Cómo empiezo con la lactancia?', a: ['El piel con piel y poner al bebé al pecho pronto y a demanda facilitan que todo arranque. Si duele o notas que algo no va bien, pide ayuda pronto a tu matrona o a un grupo de apoyo a la lactancia: casi todo tiene solución.'] },
      { draft: true, q: '¿Cuánto dura el sangrado después del parto?', a: ['El sangrado tras el parto se llama loquios. Los primeros días es como una regla abundante y después se va aclarando y disminuyendo; suele durar entre 4 y 6 semanas. Consulta si vuelve a aumentar, si empapas una compresa en una hora, si expulsas coágulos grandes o si huele mal.'] },
      { draft: true, q: '¿Cuándo tengo la revisión después del parto?', a: ['La matrona de tu centro de salud suele verte en los primeros días tras el alta y de nuevo hacia las 6 semanas (la revisión del final de la cuarentena). Es un buen momento para hablar de cómo te encuentras, la lactancia, el suelo pélvico y la anticoncepción.'] },
      { draft: true, q: '¿Cuánto dura el posparto?', a: ['El posparto (o puerperio) dura unas 6 semanas: es la «cuarentena», el tiempo que tarda el útero en volver a su tamaño y en desaparecer el sangrado. Aun así, la recuperación completa del cuerpo —el suelo pélvico, el abdomen, el cansancio— y la adaptación emocional suelen llevar varios meses. Ve a tu ritmo y pide ayuda.'] },
      { draft: true, q: '¿Qué hago con las pérdidas de orina o el suelo pélvico?', a: ['Las pérdidas de orina son frecuentes en las primeras semanas. Los ejercicios de suelo pélvico ayudan a recuperarlo; pregunta a tu matrona cómo hacerlos. Si persisten pasados unos meses, existe la fisioterapia de suelo pélvico.'] },
      { draft: true, q: '¿Cuándo y cómo se valora el suelo pélvico?', a: ['En la revisión posparto, hacia las 6 semanas, tu matrona puede valorar cómo se ha recuperado. Es recomendable una valoración con una fisioterapeuta de suelo pélvico, sobre todo si has tenido un desgarro, un parto instrumental (fórceps o ventosa) o un bebé grande. Consulta si notas:', ['Pérdidas de orina o de gases que no mejoran.', 'Sensación de peso o de «bulto» en la vagina.', 'Dolor en las relaciones sexuales.'], 'Tiene tratamiento y cuanto antes se aborde, mejor.'] },
      { draft: true, q: '¿Cuándo puedo volver a hacer ejercicio?', a: ['Puedes caminar desde los primeros días, a tu ritmo, y empezar pronto con los ejercicios de suelo pélvico. Lo habitual es:', ['Hasta la revisión de las 6 semanas: paseos, estiramientos suaves y suelo pélvico.', 'Después de la revisión: ir retomando la fuerza y el abdomen poco a poco.', 'Ejercicio de impacto (correr, saltar): no antes de unas 12 semanas y mejor tras valorar el suelo pélvico.'], 'Si has tenido una cesárea, espera a que cicatrice bien y sigue las indicaciones de tu equipo. Si notas pérdidas de orina, peso en la vagina o dolor al hacer ejercicio, para y consulta.'] },
      { draft: true, q: '¿Qué puedo tomar durante la lactancia?', a: ['La mayoría de los medicamentos son compatibles con la lactancia, y casi nunca hace falta dejar de dar el pecho para tratarte. El paracetamol y el ibuprofeno, por ejemplo, son compatibles. Para cualquier medicamento, planta o suplemento, puedes consultarlo en e-lactancia.org (de APILAM), la referencia en España, y siempre comentarlo con quien te lo receta.', { link: 'https://www.e-lactancia.org/', text: 'Consultar un medicamento en e-lactancia.org' }, 'Evita el alcohol y modera la cafeína. Si tienes dudas con un producto concreto, pregúntanos.'] },
    ],
  },
  {
    id: 'rn', title: 'El recién nacido', subtitle: 'Su peso',
    items: [
      { draft: true, q: '¿Cuánto pesa un recién nacido?', a: ['Un bebé nacido a término suele pesar entre 2,5 y 4 kg. Al nacer lo pesan y lo miden, y el dato queda anotado en su cartilla de salud: apúntalo también en Vera para seguir su evolución.'] },
      { draft: true, q: '¿Es normal que pierda peso los primeros días?', a: ['Sí. Casi todos los bebés pierden peso en los primeros días mientras se pone en marcha la alimentación. Lo habitual es perder hasta un 7 % del peso al nacer, con el punto más bajo hacia el tercer o cuarto día. Si la pérdida se acerca o supera el 10 %, tu matrona o su pediatra lo valorarán.'] },
      { draft: true, q: '¿Cuándo recupera el peso del nacimiento?', a: ['La mayoría lo recupera hacia los 10 a 14 días; algunos tardan hasta las 3 semanas. Por eso son importantes las primeras revisiones con la matrona y el pediatra.'] },
      { draft: true, q: '¿Cuánto debe ganar después?', a: ['Durante los primeros meses, de forma orientativa, entre 150 y 250 g a la semana. Cada bebé tiene su ritmo: lo importante es que siga su propia curva de crecimiento, que el pediatra valora en cada revisión.'] },
      { draft: true, q: '¿Cómo sé si come lo suficiente?', a: ['Son señales tranquilizadoras que, a partir del quinto día, moje al menos 6 pañales al día y haga deposiciones amarillas, que esté activo en las tomas y que se quede tranquilo después. Consulta pronto si moja pocos pañales, está muy dormido y cuesta despertarlo para comer, tiene la piel o los ojos cada vez más amarillos o no ha recuperado el peso al nacer a las 2 o 3 semanas.'] },
      { draft: true, q: '¿Tengo que pesarlo en casa?', a: ['No hace falta. Las básculas domésticas no son precisas y el peso de un bebé varía mucho de un día para otro (según haya comido o mojado el pañal). Es mejor apuntar los pesos que le toman en las revisiones.'] },
    ],
  },
  {
    id: 'b0', title: 'Los primeros días', subtitle: 'Cuidados del recién nacido',
    items: [
      { draft: true, q: '¿Cómo cuido el cordón umbilical?', a: ['El resto del cordón se seca y se cae solo, normalmente entre los 5 y los 15 días. Hasta entonces:', ['Mantenlo limpio y seco: si se ensucia, lávalo con agua y jabón y sécalo bien.', 'Dobla el pañal por debajo para que quede al aire.', 'No hace falta usar alcohol ni otros antisépticos salvo que te lo indiquen.', 'Es normal que manche un poco de sangre cuando se está cayendo.'], 'Consulta si la piel de alrededor se pone roja e hinchada, si supura o huele mal, si sangra más que unas gotas, si tiene fiebre o si no se ha caído a las 3 semanas.'] },
      { draft: true, q: 'Mi bebé está amarillo, ¿es normal?', a: ['Es muy frecuente: se llama ictericia y se debe a una sustancia (la bilirrubina) que el hígado del recién nacido todavía elimina despacio. Suele aparecer hacia el segundo o tercer día, empieza por la cara y desaparece sola en 1 o 2 semanas; con lactancia materna puede durar algo más. No hace falta ponerlo al sol.', 'Consulta pronto si:', ['Aparece en las primeras 24 horas.', 'El color amarillo va a más o llega a las piernas y las plantas de los pies.', 'Está muy dormido, le cuesta despertarse o come mal.', 'Hace cacas muy claras (blanquecinas) o la orina es oscura.', 'Sigue amarillo pasadas 2 semanas.']] },
      { draft: true, q: '¿Qué es normal en sus cacas y pañales?', a: ['Los primeros días hace meconio: unas cacas negras verdosas y pegajosas. Hacia el tercer a quinto día pasan a verdes y después a amarillas. Con lactancia materna suelen ser amarillo mostaza, líquidas y con grumitos, y puede hacer después de cada toma; pasado el primer mes, algunos bebés pasan varios días sin hacer, y es normal si son blandas. Con fórmula suelen ser más espesas y de color más oscuro.', 'A partir del quinto día debería mojar al menos 6 pañales al día.', 'Consulta si las cacas son blancas o grisáceas, si tienen sangre, si siguen negras después de los primeros días, si son duras como bolitas o si moja muy pocos pañales.'] },
      { draft: true, q: 'Cosas que asustan pero son normales', a: ['En las primeras semanas es habitual que el bebé:', ['Tenga hipo y estornude a menudo.', 'Eche pequeñas bocanadas de leche después de las tomas.', 'Respire de forma irregular durante el sueño, con pausas cortas de unos segundos.', 'Haga ruidos al respirar por la nariz.', 'Tiemble un poco al llorar o al sobresaltarse.', 'Tenga granitos blancos en la nariz, granitos tipo acné o la piel que se pela.', 'Tenga los pechos algo hinchados o, en las niñas, un poco de flujo o incluso un manchado vaginal, por las hormonas de la madre.'], 'Consulta si las pausas al respirar son largas o se pone azulado o pálido, si vomita con fuerza («en escopeta») o el vómito es verde, o si algo te preocupa: es mejor preguntar.'] },
      { draft: true, q: '¿Qué pruebas le hacen al nacer?', a: ['Dos cribados que se hacen a todos los recién nacidos:', ['La prueba del talón: unas gotas de sangre del talón, normalmente a partir de las 48 horas de vida, para detectar a tiempo algunas enfermedades congénitas (del metabolismo, hormonales o de la sangre). La lista exacta depende de tu comunidad.', 'La prueba de la audición: rápida e indolora, antes del alta o en las primeras semanas.'], 'Si te llaman para repetir alguna, no significa que tu bebé esté enfermo: muchas veces es porque la muestra no fue suficiente o porque tenía líquido en el oído al nacer. Haz la repetición cuanto antes.'] },
      { draft: true, q: '¿Cómo lo baño y le corto las uñas?', a: ['No hace falta bañarlo todos los días: dos o tres veces por semana es suficiente al principio, aunque si le relaja puedes hacerlo a diario.', ['Prepara todo antes y no lo dejes solo ni un segundo.', 'Agua templada, a unos 37 °C: compruébala con el codo.', 'Baños cortos, de 5 a 10 minutos, con poco jabón suave.', 'Seca bien los pliegues y, si su piel está seca, usa una crema hidratante sin perfume.'], 'Para las uñas, las primeras semanas mejor una lima de cartón. Después, unas tijeras de punta redonda, con las uñas rectas y mejor mientras duerme.'] },
    ],
  },
  {
    id: 'bal', title: 'Alimentar a tu bebé', subtitle: 'Pecho, biberón y vitamina D',
    items: [
      { draft: true, q: '¿Cómo sé si la lactancia va bien?', a: ['Los primeros días los bebés maman a demanda, unas 8 a 12 veces al día. Ofrécele el pecho con las primeras señales de hambre (se lleva las manos a la boca, gira la cabeza buscando, hace chupeteo), antes de que llore.', 'Señales de un buen agarre:', ['Boca muy abierta, con los labios hacia fuera.', 'Coge más areola por debajo que por arriba.', 'Mejillas redondeadas, sin hoyuelos.', 'Lo oyes tragar y a ti no te duele.'], 'Va bien si moja suficientes pañales, hace cacas amarillas y va ganando peso. Si duele, salen grietas o tienes dudas, pide ayuda pronto a tu matrona o a un grupo de apoyo a la lactancia: casi todo tiene solución.'] },
      { draft: true, q: '¿Cómo preparo el biberón?', a: ['Usa una leche de inicio y sigue las instrucciones del envase:', ['Lávate las manos y usa biberones y tetinas limpios.', 'Pon primero el agua (apta para lactantes) y después los cacitos rasos que indique el envase: nunca añadas polvo de más ni de menos.', 'Agita bien y comprueba la temperatura con unas gotas en la muñeca. Evita el microondas, porque calienta de forma desigual.', 'Desecha la leche que sobre en la toma.'], 'Las cantidades del envase son orientativas: ofrécelo cuando muestre hambre y respeta cuando no quiere más. Su pediatra te dirá qué agua usar y si hace falta esterilizar.'] },
      { draft: true, q: '¿Tiene que tomar vitamina D?', a: ['Sí. Se recomienda que todos los bebés tomen un suplemento de vitamina D durante el primer año, habitualmente 400 UI al día, porque la leche aporta poca y no deben tomar el sol directamente. Su pediatra te indicará cuál, desde cuándo y cómo dárselo en la primera revisión.'] },
      { draft: true, q: 'Lactancia mixta y cómo guardar la leche', a: ['Si combinas pecho y biberón, ofrece primero el pecho y completa después si hace falta: así mantienes la producción de leche. Tu matrona puede ayudarte a ajustarlo.', 'Para guardar la leche materna que te extraigas (en recipientes limpios y con la fecha):', ['A temperatura ambiente: hasta 4 horas.', 'En la nevera, al fondo y no en la puerta: hasta 4 días.', 'En el congelador (−18 °C): unos 6 meses.'], 'Descongélala en la nevera o al baño maría, nunca en el microondas, úsala en 24 horas y no la vuelvas a congelar.'] },
      { draft: true, q: '¿Puede tomar agua, zumos o infusiones?', a: ['Antes de los 6 meses no necesita agua, ni siquiera con calor: la leche, a demanda, le da todo lo que necesita. A partir de los 6 meses, con la alimentación complementaria, puedes ofrecerle agua en vaso.', 'Los zumos no se recomiendan: es mejor la fruta entera. Tampoco las infusiones, porque algunas plantas pueden ser peligrosas para un bebé (por ejemplo, el anís estrellado). Y nada de miel antes del año.'] },
    ],
  },
  {
    id: 'bsl', title: 'Sueño, llanto y seguridad', subtitle: 'Para dormir tranquilos',
    items: [
      { draft: true, q: '¿Cómo duerme seguro mi bebé?', a: ['Estas medidas reducen el riesgo de muerte súbita del lactante:', ['Siempre boca arriba para dormir, también en las siestas.', 'En una cuna con colchón firme y sin almohadas, peluches, protectores ni mantas sueltas.', 'En vuestra habitación, en su propia cuna, al menos los primeros 6 meses.', 'Sin abrigarlo de más ni taparle la cabeza.', 'Sin humo de tabaco, ni en casa ni en el coche.'], 'La lactancia materna también protege. Si duermes con él en tu cama, evita siempre hacerlo en un sofá o sillón, si fumas, si has bebido alcohol o tomas medicación que dé sueño, o si es prematuro o de bajo peso. Despierto y vigilado, ponerlo boca abajo un rato cada día le ayuda a fortalecerse.'] },
      { draft: true, q: 'Llora mucho, ¿son cólicos?', a: ['Todos los bebés lloran, y el llanto suele aumentar hasta las 6 a 8 semanas y mejorar hacia los 3 o 4 meses. Se habla de cólicos cuando un bebé sano, que come y gana peso, llora de forma intensa y difícil de calmar durante horas, sobre todo por la tarde.', 'Lo que suele ayudar:', ['Comprobar si tiene hambre, frío, calor o el pañal sucio.', 'Cogerlo en brazos, mecerlo, el contacto piel con piel o el portabebés.', 'Un ruido suave y constante, un paseo o un baño templado.'], 'Turnaos y descansad cuando podáis. Consulta si el llanto es muy distinto al habitual, si tiene fiebre, vomita, come mal o no gana peso.'] },
      { draft: true, q: 'Nunca lo zarandees', a: ['Sacudir a un bebé, aunque sea un momento, puede causarle un daño cerebral grave (síndrome del bebé zarandeado). Si el llanto te supera, es normal y no es culpa tuya:', ['Déjalo en un lugar seguro, en su cuna y boca arriba.', 'Sal de la habitación unos minutos, respira y bebe agua.', 'Llama a alguien de confianza para que te releve o te acompañe.'], 'Un bebé que llora unos minutos en su cuna está a salvo. Si te sientes así a menudo, coméntalo con tu matrona o tu pediatra: pedir ayuda es cuidar de los dos.'] },
      { draft: true, q: '¿Cuánto duerme un bebé?', a: ['Mucho, pero a ratos. De forma orientativa:', ['Recién nacido: entre 14 y 17 horas al día, en periodos cortos de día y de noche.', 'De los 4 a los 12 meses: entre 12 y 16 horas, contando las siestas.'], 'Despertarse por la noche es normal durante el primer año, sobre todo para comer. Una rutina tranquila antes de dormir (baño, luz tenue, toma, canción) le ayuda a distinguir el día de la noche. Cada bebé tiene su ritmo: si te preocupa su sueño, coméntalo en la revisión.'] },
      { draft: true, q: '¿Cómo lo llevo en el coche?', a: ['Siempre en su silla homologada, desde el primer viaje al salir del hospital, aunque sea un trayecto corto:', ['Mirando hacia atrás (a contramarcha): es lo más seguro, y conviene mantenerlo así el mayor tiempo posible.', 'Mejor en el asiento de atrás. Si va delante, desactiva el airbag del copiloto.', 'Arneses bien ajustados y sin abrigos gruesos debajo: tápalo por encima.', 'En los primeros meses, haz paradas en los viajes largos para sacarlo de la silla.']] },
      { draft: true, q: 'Cómo evitar accidentes en casa', a: ['Los más frecuentes en el primer año son las caídas, los atragantamientos y las quemaduras:', ['No lo dejes solo en el cambiador, la cama o el sofá: se puede caer aunque aún no se dé la vuelta.', 'Mantén fuera de su alcance objetos pequeños, bolsas de plástico y cordones.', 'No bebas ni lleves líquidos calientes con el bebé en brazos y comprueba siempre la temperatura del agua.', 'Medicamentos y productos de limpieza, guardados y fuera de su alcance.', 'No se recomienda el andador.'], 'Si se toma algo que puede ser tóxico, llama al Servicio de Información Toxicológica: 91 562 04 20.'] },
      { draft: true, q: '¿Le doy chupete?', a: ['Puede ayudarle a calmarse y, usado para dormir, se asocia a menos riesgo de muerte súbita. Si das el pecho, mejor esperar a que la lactancia esté bien establecida, hacia las 3 o 4 semanas.', ['Si no lo quiere, no le obligues.', 'Nunca lo mojes en azúcar ni en miel.', 'Límpialo a menudo y no lo cuelgues de cordones largos.', 'A partir del año, ve retirándolo poco a poco.']] },
      { draft: true, q: 'Sol y calor', a: ['Su piel es muy delicada y regula peor la temperatura:', ['Antes de los 6 meses, nada de sol directo: sombra, ropa ligera de manga larga y gorro. A esa edad no se recomiendan las cremas solares salvo en zonas pequeñas si no hay alternativa.', 'A partir de los 6 meses, protector solar infantil de factor alto, además de la sombra, la ropa y el gorro.', 'Evita salir en las horas centrales del día en verano.', 'Con calor, no lo abrigues de más y ofrécele el pecho o el biberón más a menudo.', 'No cubras el cochecito con una tela o una manta: dentro sube mucho la temperatura.', 'Nunca lo dejes solo en el coche, ni un momento.']] },
    ],
  },
  {
    id: 'bb', title: 'Tu bebé', subtitle: 'Salud, vacunas y alimentación',
    items: [
      { draft: true, q: '¿Cuándo debo ir a urgencias con mi bebé?', a: ['Llévalo a urgencias, o llama al 112 si es grave, si notas:', ['Fiebre de 38 °C o más en un bebé menor de 3 meses.', 'Dificultad para respirar: respira muy deprisa, se le hunden las costillas o se pone de color azulado.', 'Está muy adormilado, cuesta despertarlo o está muy decaído.', 'Rechaza varias tomas seguidas o vomita todo, sobre todo si el vómito es verdoso.', 'Moja muy pocos pañales.', 'Tiene la piel o los ojos amarillos en las primeras 24 horas, o el color amarillo va a más.', 'Tiene convulsiones o movimientos extraños.', 'Llora de forma muy distinta a lo habitual y no hay manera de calmarlo.'], 'Ante la duda, consulta: con un recién nacido siempre es mejor que lo valoren.'] },
      { draft: true, q: 'Tiene fiebre, ¿qué hago?', a: ['Hablamos de fiebre a partir de 38 °C. Mídela con un termómetro digital en la axila.', ['Si tiene menos de 3 meses y 38 °C o más, llévalo siempre a urgencias, aunque parezca estar bien.', 'Entre los 3 y los 6 meses, consulta con su pediatra ese mismo día.', 'Más mayor, lo importante es cómo está: si juega y come entre los picos de fiebre, puedes vigilarlo en casa.'], 'No lo abrigues de más y ofrécele tomas a menudo. Los medicamentos para la fiebre, solo con la dosis según su peso que te indique su pediatra; nunca aspirina. Consulta enseguida si está muy decaído o le cuesta despertarse, respira con dificultad, le salen manchas en la piel que no desaparecen al estirarla, rechaza las tomas o la fiebre dura más de 48 horas.'] },
      { draft: true, q: '¿Qué revisiones tiene en el primer año?', a: ['Con el Programa de Salud Infantil de tu centro de salud. La primera visita es en los primeros días de vida y después suele haber revisiones hacia el mes y a los 2, 4, 6, 9 y 12 meses, muchas veces coincidiendo con las vacunas; el calendario exacto depende de tu comunidad.', 'En cada revisión se mide su peso, su talla y su cabeza, se valora su desarrollo, su alimentación y su sueño, se revisan las caderas, la vista y el oído, y se ponen las vacunas que tocan. Llévate tus dudas apuntadas y guarda las citas en Cuidados → Agenda.'] },
      { draft: true, q: '¿Qué vacunas le tocan a mi bebé?', a: ['En los primeros días de vida y en temporada de virus respiratorio sincitial (VRS) le pueden poner un anticuerpo que le protege de la bronquiolitis. Las primeras vacunas del calendario son a los 2 meses, y después siguen a los 4 y a los 11–12 meses, entre otras. Tu centro de salud te dará cita. El calendario exacto cambia según el año y tu comunidad autónoma, así que consúltalo en las fuentes oficiales:', { link: 'https://www.sanidad.gob.es/areas/promocionPrevencion/vacunaciones/calendario/home.htm', text: 'Calendario de vacunación del Ministerio de Sanidad' }, { link: 'https://vacunasaep.org/familias/calendario-de-vacunaciones', text: 'Calendario explicado para familias (Asociación Española de Pediatría)' }] },
      { draft: true, q: '¿Cuándo empieza a comer otros alimentos?', a: ['Hacia los 6 meses, sin dejar la leche (materna o de fórmula), que sigue siendo su alimento principal durante el primer año. Suele estar preparado cuando se mantiene sentado con poco apoyo, muestra interés por la comida y ya no expulsa los alimentos con la lengua.', ['Puedes ofrecer purés o trozos blandos adaptados a su edad: las dos formas son válidas.', 'Incluye pronto alimentos ricos en hierro (carne, legumbres, huevo, pescado).', 'Sin sal ni azúcar añadidos, y nada de miel antes del año.', 'No hace falta retrasar los alimentos que pueden dar alergia (huevo, pescado, frutos secos molidos); introdúcelos de uno en uno.', 'Evita los frutos secos enteros y los trozos duros y redondos por el riesgo de atragantamiento.'], 'Tu pediatra te orientará en la revisión de los 6 meses.'] },
    ],
  },
  {
    id: 'bsal', title: 'Su salud', subtitle: 'Catarros, tripa y piel',
    items: [
      { draft: true, q: 'Mocos, tos y bronquiolitis', a: ['Los catarros son muy frecuentes, sobre todo en invierno o si tiene hermanos o va a la guardería. Lo que más ayuda:', ['Lavados nasales con suero fisiológico antes de las tomas y de dormir.', 'Tomas más pequeñas y más frecuentes.', 'Un ambiente sin humo de tabaco.'], 'La bronquiolitis es una infección de los bronquios pequeños, frecuente en menores de 2 años. Consulta si respira muy deprisa, se le hunden las costillas o se le marca el cuello al respirar, hace pausas o se pone azulado, rechaza la mitad de las tomas o más, tiene menos de 3 meses o tiene fiebre alta.'] },
      { draft: true, q: 'Vómitos y diarrea: ¿cuándo preocuparse?', a: ['Lo importante es que no se deshidrate. Sigue con el pecho o el biberón, ofreciéndolo más a menudo y en menos cantidad. Si te lo indica su pediatra, usa un suero oral de farmacia; no le des bebidas para deportistas ni refrescos.', 'Consulta pronto si tiene menos de 3 meses, si vomita todo o el vómito es verde o con sangre, si hay sangre en las cacas, o si notas signos de deshidratación: moja muchos menos pañales, tiene la boca seca, llora sin lágrimas, la fontanela está hundida o está muy decaído.'] },
      { draft: true, q: 'Su piel: pañal, costra láctea y eccema', a: [['Dermatitis del pañal (culito rojo): cambia el pañal a menudo, limpia con agua, seca bien, usa una pasta protectora y déjalo ratos sin pañal. Consulta si no mejora en 2 o 3 días o aparecen granitos rojos alrededor.', 'Costra láctea: escamas amarillentas en el cuero cabelludo. Es inofensiva: puedes ablandarla con un poco de aceite y retirarla con un cepillo suave, sin arrancarla.', 'Eccema (dermatitis atópica): piel seca, áspera y con picor. Ayudan los baños cortos, la crema hidratante sin perfume varias veces al día y la ropa de algodón. Coméntalo con su pediatra.']] },
      { draft: true, q: '¿Qué es el muguet?', a: ['Son unas placas blancas en la lengua, las encías o el interior de las mejillas que, a diferencia de los restos de leche, no se quitan al frotar. Lo produce un hongo y es frecuente en los primeros meses. Su pediatra le pautará un tratamiento.', 'Si das el pecho, el hongo puede pasar a los pezones (dolor, picor o enrojecimiento): consulta para tratar a los dos a la vez. Lava bien chupetes y tetinas.'] },
    ],
  },
  {
    id: 'bdes', title: 'Su desarrollo', subtitle: 'Hitos, cabeza y dientes',
    items: [
      { draft: true, q: '¿Qué hace un bebé en cada etapa?', a: ['Cada bebé tiene su ritmo y estas edades son orientativas (si nació prematuro, cuenta su edad corregida):', ['1–2 meses: sonríe cuando le hablas y sigue las caras con la mirada.', '3–4 meses: sostiene la cabeza, ríe y se lleva las manos a la boca.', '6 meses: se da la vuelta, se sienta con apoyo y balbucea.', '9 meses: se sienta solo, coge cosas pequeñas con los dedos y reconoce su nombre.', '12 meses: se pone de pie agarrado, dice alguna palabra y señala lo que quiere. Los primeros pasos llegan entre los 9 y los 18 meses.'], 'Consulta si no sonríe a los 3 meses, no sostiene la cabeza a los 4, no se sienta a los 9, no reacciona a los sonidos o deja de hacer algo que ya hacía.'] },
      { draft: true, q: 'Tiempo boca abajo y cabeza plana', a: ['Dormir boca arriba es lo más seguro, pero puede aplanarle un poco la parte de atrás de la cabeza (plagiocefalia). Para evitarlo:', ['Ponlo boca abajo, despierto y vigilado, varias veces al día desde las primeras semanas: empieza con uno o dos minutos y ve aumentando.', 'Alterna hacia qué lado mira en la cuna.', 'Cógelo en brazos o en el portabebés y limita el tiempo en hamacas y sillas.'], 'Consulta si ves un aplanamiento marcado o si siempre gira la cabeza hacia el mismo lado.'] },
      { draft: true, q: 'Los dientes', a: ['El primer diente suele salir hacia los 6 meses, aunque es normal entre los 4 y los 15. Puede babear más, morderlo todo y estar algo irritable: ayudan un mordedor frío (no congelado) y masajearle la encía con el dedo limpio. No se recomiendan los geles anestésicos.', 'La fiebre alta o la diarrea no se deben a los dientes: si aparecen, consulta. Desde el primer diente, cepíllaselos dos veces al día con una pasta con flúor (1000 ppm), en cantidad como un grano de arroz.'] },
      { draft: true, q: 'Juego, cuentos y pantallas', a: ['Lo que más le estimula eres tú: háblale, cántale y respóndele cuando hace sonidos desde los primeros días. Leerle cuentos, aunque todavía no los entienda, favorece el lenguaje. Déjale tiempo en el suelo para que se mueva y ofrécele juguetes sencillos y seguros, adecuados a su edad.', 'Las pantallas no se recomiendan antes de los 2 años (las videollamadas con la familia son la excepción). Evita también la televisión encendida de fondo mientras juega.'] },
    ],
  },
  {
    id: 'bfam', title: 'Vida en familia', subtitle: 'Trabajo y guardería',
    items: [
      { draft: true, q: 'Volver al trabajo dando el pecho', a: ['Es posible mantener la lactancia al volver al trabajo:', ['Empieza a extraerte y congelar leche dos o tres semanas antes.', 'Practica antes de la vuelta que otra persona le dé tu leche (con vaso, cuchara o biberón).', 'Si puedes, extráete leche en el trabajo; las tomas al llegar a casa y por la noche ayudan a mantener la producción.'], 'Hasta que el bebé cumple 9 meses tienes derecho al permiso por cuidado del lactante: una hora de ausencia al día (que se puede dividir), reducir la jornada media hora o, si lo permite tu convenio o lo acuerdas con tu empresa, acumularlo en días completos. Consulta tu convenio.'] },
      { draft: true, q: 'La guardería y las primeras infecciones', a: ['El primer año de guardería es normal que se ponga malito a menudo: catarros, otitis o gastroenteritis, a veces uno detrás de otro. Su sistema de defensas está aprendiendo, y suele mejorar a partir del segundo año.', ['Haz una adaptación progresiva los primeros días, si es posible.', 'Mantén sus vacunas al día y lavaos las manos a menudo en casa.', 'Si tiene fiebre, vómitos o diarrea o está decaído, mejor que se quede en casa; sigue las normas de tu escuela infantil.'], 'Si las infecciones son muy frecuentes, muy intensas o no gana peso, coméntalo con su pediatra.'] },
    ],
  },
  {
    id: 'ppc', title: 'La regla y la anticoncepción', subtitle: 'Cuando vuelva tu ciclo',
    items: [
      { draft: true, q: '¿Cuándo vuelve la regla?', a: ['Si no das el pecho, suele volver entre 6 y 8 semanas después del parto. Si das lactancia materna, puede tardar meses, sobre todo si es exclusiva. Los primeros ciclos suelen ser irregulares, así que las predicciones de Vera serán poco fiables hasta que registres dos o tres reglas.'] },
      { draft: true, q: '¿La lactancia protege de un nuevo embarazo?', a: ['Solo de forma limitada: puedes ovular antes de tener la primera regla. Si no quieres un nuevo embarazo, habla de anticoncepción con tu matrona o tu médico antes de retomar las relaciones; hay métodos compatibles con la lactancia.'] },
    ],
  },
];

/** Sección de la guía que corresponde a una semana de embarazo */
export function guideSectionFor(weeks) {
  return PREGNANCY_GUIDE.find((s) => s.id !== 'emo' && weeks >= s.from && weeks <= s.to)
    ?? (weeks < 4 ? PREGNANCY_GUIDE[0] : PREGNANCY_GUIDE.find((s) => s.id === 's37'));
}
